config/routes.rb
Rails.application.routes.draw do
  resources :original_photos
  #get 'welcome/about'
  mount Lockup::Engine, at: '/lockup'
  devise_for :users

  mount ImageUploader.derivation_endpoint => "/derivations/image"

  resources :categories
  resources :photos do
    resources :original_photos, except: [:index]
  end
  resources :search_photos
  resources :sort_photos

  root "welcome#about"
end

app/controllers/sort_photos_controller.rb
class SortPhotosController < ApplicationController

  def index
    @photos = Photo.all.order(:sort)
  end

  def update
    photo = Photo.find(params[:id])
    Photo.swap_sort(photo, params[:pos].to_i)
    @photos = Photo.all.order(:sort)
    
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/sort_photos_helper.rb
module SortPhotosHelper
  def sort_up(photo)
    photo.sort.present? && photo.sort > 1
  end

  def sort_down(photo)
    photo.sort.present? && photo.sort < Photo.max_sort
  end
end

app/views/sort_photos/_index.html.erb
<% photos.each do |photo| %>
  <div class="btn-group-vertical btn-group-sm border-left border-right" role="group">
    <%= render 'sort_photos/photo', photo: photo %>
  </div>
<% end %>

app/views/sort_photos/_photo.html.erb
<div class="col mt-0 pt-0">
  <div class="card text-bg-dark border border-danger mb-3 pb-3">
    <% if photo.image_data? %>
      <a href="<%= photo_path(photo) %>">
        <img src="<%= photo.image_url(:medium) %>" class="card-img-top bg-danger" alt="...">
      </a>
      <div class="card-body bg-dark">
        <%= render 'sort_photos/sorter', photo: photo %><span class="fs-6"><%= photo.title %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/sort_photos/_sorter.html.erb
<%= link_to_if sort_up(photo), "<i class='fa-solid fa-angle-up'></i>".html_safe, sort_photo_path(photo, pos: -1), method: :put, remote: true %>
<%= link_to_if sort_down(photo), "<i class='fa-solid fa-angle-down'></i>".html_safe, sort_photo_path(photo, pos: 1), method: :put, remote: true %>

app/views/sort_photos/index.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4 mt-3 bg-dark justify-content-center" id="sort-photos-index">
  <%= render 'sort_photos/index', photos: @photos %>
</div>

app/views/sort_photos/update.js.erb
$("#sort-photos-index").html('<%= j render "sort_photos/index", photos: @photos %>');