config/routes.rb
Rails.application.routes.draw do
  resources :original_photos
  #get 'welcome/about'
  mount Lockup::Engine, at: '/lockup'
  devise_for :users

  mount ImageUploader.derivation_endpoint => "/derivations/image"

  resources :categories
  resources :photos do
    resources :original_photos, except: [:index]
  end
  resources :search_photos
  resources :sort_photos

  root "welcome#about"
end

app/models/original_photo.rb
require "./app/uploaders/image_uploader"

class OriginalPhoto < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :photo
end

app/controllers/original_photos_controller.rb
class OriginalPhotosController < ApplicationController
  before_action :set_original_photo, only: %i[ show edit update destroy ]
  before_action :set_photo, only: %i[ new create destroy]
  # GET /original_photos/1 or /original_photos/1.json
  def show
  end

  # GET /original_photos/new
  def new
    @original_photo = OriginalPhoto.new
  end

  # GET /original_photos/1/edit
  def edit
  end

  # POST /original_photos or /original_photos.json
  def create
    #@original_photo = OriginalPhoto.new
    @original_photo = @photo.build_original_photo(original_photo_params)

    respond_to do |format|
      if @original_photo.save
        format.html { redirect_to original_photo_url(@original_photo), notice: "Original photo was successfully created." }
        format.json { render :show, status: :created, location: @original_photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @original_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /original_photos/1 or /original_photos/1.json
  def update
    respond_to do |format|
      if @original_photo.update(original_photo_params)
        format.html { redirect_to original_photo_url(@original_photo), notice: "Original photo was successfully updated." }
        format.json { render :show, status: :ok, location: @original_photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @original_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /original_photos/1 or /original_photos/1.json
  def destroy
    @original_photo.destroy

    respond_to do |format|
      format.html { redirect_to @photo, notice: "Original photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_original_photo
      @original_photo = OriginalPhoto.find(params[:id])
    end

    def set_photo
      @photo = Photo.find(params[:photo_id])
    end

    # Only allow a list of trusted parameters through.
    def original_photo_params
      params.require(:original_photo).permit(:image, :photo_id)
    end
end

app/helpers/original_photos_helper.rb
module OriginalPhotosHelper
end

app/views/original_photos/_form.html.erb
<%= form_with(model: original_photo, url: [photo, original_photo], local: true) do |form| %>
  <% if original_photo.persisted? && original_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(original_photo.errors.count, "error") %> prohibited this original_photo from being saved:</h2>

      <ul>
      <% original_photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= image_tag form.object.image_url if form.object.cached_image_data %>
    <%= form.hidden_field :image, value: form.object.cached_image_data %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if original_photo.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', [photo, original_photo], method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if original_photo.persisted? %>
      <%#= link_to "Cancel", original_photo, class: "btn btn-link" %>
    <% else %>
      <%#= link_to "Cancel", original_photos_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/original_photos/_original_photo.html.erb
<div class="col-6">
  <% if original_photo && original_photo.image_data? %>
    <dl class="dl-horizontal">
      <dd><%= image_tag original_photo.image_url(:small) if original_photo.image %></dd>
      <%= link_to "Edit", edit_photo_original_photo_path(original_photo.photo, original_photo) %></dd>
      <%= link_to 'Destroy', [original_photo.photo, original_photo], method: :delete, class: "text-warning", data: { confirm: 'Are you sure?' } %>
    </dl>
  <% end %>
</div>

app/views/original_photos/edit.html.erb
<h1>Editing original photo</h1>

<%= render "form", original_photo: @original_photo %>

<br>

<div>
  <%= link_to "Show this original photo", @original_photo %> |
  <%= link_to "Back to original photos", original_photos_path %>
</div>

app/views/original_photos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Original photos</h1>

<div id="original_photos">
  <% @original_photos.each do |original_photo| %>
    <%= render original_photo %>
    <p>
      <%= link_to "Show this original photo", original_photo %>
    </p>
  <% end %>
</div>

<%= link_to "New original photo", new_original_photo_path %>

app/views/original_photos/new.html.erb
<h1>New original photo</h1>

<%= render "form", original_photo: @original_photo %>

<br>

<div>
  <%= link_to "Back to original photos", original_photos_path %>
</div>

app/views/original_photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @original_photo %>

<div>
  <%= link_to "Edit this original photo", edit_original_photo_path(@original_photo) %> |
  <%= link_to "Back to original photos", original_photos_path %>

  <%= button_to "Destroy this original photo", @original_photo, method: :delete %>
</div>