config/routes.rb
Rails.application.routes.draw do
  resources :original_photos
  #get 'welcome/about'
  mount Lockup::Engine, at: '/lockup'
  devise_for :users

  mount ImageUploader.derivation_endpoint => "/derivations/image"

  resources :categories
  resources :photos do
    resources :original_photos, except: [:index]
  end
  resources :search_photos
  resources :sort_photos

  root "welcome#about"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark fixed-top mb-5">
  <div class="container-fluid">

    <a class="navbar-brand sexy_text text-warning fs-1" href="#">Josh Exotic's Prviate Parts</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="d-flex">
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="<%= photos_path %>" class="nav-link text-warning">
              Photos
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= categories_path %>" class="nav-link text-warning">
              Categories
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= new_photo_path %>" class="nav-link text-warning">
              Add New Photo
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= new_category_path %>" class="nav-link text-warning">
              Add Categories
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= sort_photos_path %>" class="nav-link text-warning">
              Sort Photos
            </a>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link text-warning" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<br>
<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Josh Exotic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-danger">
    <div class="container">
      <% if user_signed_in? %>
        <%= render "layouts/navbar" %>
      <% end %>

      <%= yield %>
      <% unless user_signed_in? %>
        <img src="../../../assets/mural.png" class="img-fluid" alt="...">
      <% end %>
    </div>

  </body>
</html>